server:
  shutdown: immediate

hmpps:
  auth:
    url: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    timeout: 10s
  sqs:
    enabled: true
    provider: localstack
    queues:
      prisonvisitsnotificationalerts:
        queueName: ${random.uuid}
        dlqName: ${random.uuid}
        subscribeTopicId: domainevents
        dlqMaxReceiveCount: 1
        visibilityTimeout: 1
    topics:
      domainevents:
        arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}

visit-scheduler.api.url: http://localhost:8081

prison-register.api.url: https://prison-register-dev.hmpps.service.justice.gov.uk

prisoner-contact.registry.url: https://prisoner-contact-registry-dev.prison.service.justice.gov.uk

prisoner:
  offender:
    search:
      url: https://prisoner-search-dev.prison.service.justice.gov.uk
      timeout: 10s

notify.sms.enabled: true
notify.api.key: dummy-api-key