generic-service:
  nameOverride: hmpps-notifications-alerts-vsip
  serviceAccountName: visit-someone-in-prison
  productId: "DPS035"
  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-notifications-alerts-vsip
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-notifications-alerts-vsip-cert

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    HMPPS_SQS_USE_WEB_TOKEN: "true"
    HMPPS_SQS_ENABLED: "true"
    NOTIFY_SMS_ENABLED: "true"
    NOTIFY_EMAIL_ENABLED: "true"
  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    hmpps-notifications-alerts-vsip:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      SYSTEM_CLIENT_ID: "SYSTEM_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
      NOTIFY_API_KEY: "NOTIFY_API_KEY"
      NOTIFY_CALLBACK_TOKEN: "NOTIFY_CALLBACK_TOKEN"
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_DOMAINEVENTS_ARN: "topic_arn"
    sqs-prison-visits-notification-alerts-secret:
      HMPPS_SQS_QUEUES_PRISONVISITSNOTIFICATIONALERTS_QUEUE_NAME: "sqs_queue_name"
    sqs-hmpps-prison-visits-notification-alerts-dlq-secret:
      HMPPS_SQS_QUEUES_PRISONVISITSNOTIFICATIONALERTS_DLQ_NAME: "sqs_queue_name"

  allowlist:
    gov-notify-1: 52.17.149.153
    gov-notify-2: 63.33.132.231
    gov-notify-3: 54.216.159.202
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-notifications-alerts-vsip
