---
# Per environment values which override defaults in hmpps-notifications-alerts-vsip/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-notifi-alerts-vsip.prison.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    SPRING_PROFILES_ACTIVE: "stdout"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    VISIT-SCHEDULER_API_URL: https://visit-scheduler.prison.service.justice.gov.uk
    PRISONER_OFFENDER_SEARCH_URL: https://prisoner-search.prison.service.justice.gov.uk
    PRISONER-CONTACT_REGISTRY_URL: https://prisoner-contact-registry.prison.service.justice.gov.uk
    PRISON-REGISTER_API_URL: https://prison-register.hmpps.service.justice.gov.uk

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: visits-alerts
  sqsAlertsQueueNames:
    - "book-a-prison-visit-prod-hmpps_prison_visits_notification_alerts_queue"
    - "book-a-prison-visit-prod-hmpps_prison_visits_notification_alerts_dlq"
  sqsAlertsOldestThreshold: 1
  sqsAlertsTotalMessagesThreshold: 1
