---
# Per environment values which override defaults in hmpps-notifications-alerts-vsip/values.yaml

generic-service:
  ingress:
    host: hmpps-notifications-alerts-vsip.hmpps.service.justice.gov.uk

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service
